complete -c bob -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c bob -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c bob -n "__fish_use_subcommand" -f -a "use" -d 'Switch to the specified version, by default will auto-invoke install command if the version is not installed already'
complete -c bob -n "__fish_use_subcommand" -f -a "install" -d 'Install the specified version, can also be used to update out-of-date nightly version'
complete -c bob -n "__fish_use_subcommand" -f -a "sync" -d 'If Config::version_sync_file_location is set, the version in that file will be parsed and installed'
complete -c bob -n "__fish_use_subcommand" -f -a "uninstall" -d 'Uninstall the specified version'
complete -c bob -n "__fish_use_subcommand" -f -a "rm" -d 'Uninstall the specified version'
complete -c bob -n "__fish_use_subcommand" -f -a "rollback" -d 'Rollback to an existing nightly rollback'
complete -c bob -n "__fish_use_subcommand" -f -a "erase" -d 'Erase any change bob ever made, including neovim installation, neovim version downloads and registry changes'
complete -c bob -n "__fish_use_subcommand" -f -a "list" -d 'List all installed and used versions'
complete -c bob -n "__fish_use_subcommand" -f -a "ls" -d 'List all installed and used versions'
complete -c bob -n "__fish_use_subcommand" -f -a "list-remote"
complete -c bob -n "__fish_use_subcommand" -f -a "ls-remote"
complete -c bob -n "__fish_use_subcommand" -f -a "complete" -d 'Generate shell completion'
complete -c bob -n "__fish_use_subcommand" -f -a "update" -d 'Update existing version |nightly|stable|--all|'
complete -c bob -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bob -n "__fish_seen_subcommand_from use" -s n -l no-install -d 'Whether not to auto-invoke install command'
complete -c bob -n "__fish_seen_subcommand_from use" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from sync" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from rm" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from rollback" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from erase" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from ls" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from list-remote" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from ls-remote" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from complete" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from update" -s a -l all -d 'Apply the update to all versions'
complete -c bob -n "__fish_seen_subcommand_from update" -s h -l help -d 'Print help'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "use" -d 'Switch to the specified version, by default will auto-invoke install command if the version is not installed already'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "install" -d 'Install the specified version, can also be used to update out-of-date nightly version'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "sync" -d 'If Config::version_sync_file_location is set, the version in that file will be parsed and installed'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "uninstall" -d 'Uninstall the specified version'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "rollback" -d 'Rollback to an existing nightly rollback'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "erase" -d 'Erase any change bob ever made, including neovim installation, neovim version downloads and registry changes'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "list" -d 'List all installed and used versions'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "list-remote"
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "complete" -d 'Generate shell completion'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "update" -d 'Update existing version |nightly|stable|--all|'
complete -c bob -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from use install sync uninstall rollback erase list list-remote complete update help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
